### ISSUE TITLE
Archive this project

### ISSUE THREAD

**Issue by sillygwailo** [backdrop-contrib/ayah#1]
The service that this integrates with is defunct, so can we archive this project?

**Comment by stpaultim** [comment]
I think this might be the best way/place to get a response from someone with access to archive a project. 
https://github.com/backdrop-ops/contrib/issues/391

**Comment by serundeputy** [comment]
In the settings tab for the repo there is an archive button; someone with access to the settings tab needs to push it. Prolly @klonos or someone on contrib squad;

**Comment by jenlampton** [comment]
I was going to recommend that we update the README.md before archiving, but it looks like someone has already done that :) Thank you @sillygwailo
